name: Delete old feature branches and close PRs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete old branches and close PRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          DAYS_THRESHOLD=1
          git fetch --prune origin

          for branch in $(git branch -r | grep 'origin/feature/' | sed 's|origin/||'); do
              echo "Checking branch: $branch"

              last_commit_date=$(git log -1 --format="%ct" origin/$branch)
              current_date=$(date +%s)
              diff_days=$(( (current_date - last_commit_date) / 86400 ))

              if [ "$diff_days" -gt "$DAYS_THRESHOLD" ]; then
                  prs=$(gh pr list --head "$branch" --state=open --json number --jq '.[].number')

                  if [ -n "$prs" ]; then
                      echo "Closing PRs for branch $branch: $prs"
                      for pr_number in $prs; do
                          gh pr close "$pr_number" --comment "Auto-closing PR because the feature branch is older than ${DAYS_THRESHOLD} day(s)."
                      done
                  fi

                  echo "Deleting branch $branch"
                  git push origin --delete "$branch"
              else
                  echo "Branch $branch is fresh. Skipping."
              fi
          done
