name: PR Label Actions

on:
  pull_request:
    types: [ labeled ]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  auto_merge_label:
    if: ${{ github.event.label.name == 'auto-merge' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ env.PR_NUMBER }}
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: 'auto-merge'
          MERGE_RETRIES: "12"
          MERGE_RETRY_SLEEP: "10000"
